ChartBoost/chartboost-mediation-ios-adapter-admob

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- README.md
- Source/AdMobAdapter.swift
Adapter version '4.10.9.0.0', partner version '~> 10.9.0'
> Update Version to 4.10.9.0.0

- Source/AdMobAdapterConfiguration.swift
https://chartboost.atlassian.net/browse/HB-5933
> HB-5933: use os_log instead of print

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
- Source/AdMobAdapterBannerAd.swift
Adapter version '4.10.9.0.1', partner version '~> 10.9.0'
> Update Version to 4.10.9.0.1

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.10.10.0.0', partner version '~> 10.10.0'
> Update Version to 4.10.10.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.10.11.0.0', partner version '~> 10.11.0'
> Update Version to 4.10.11.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.10.12.0.0', partner version '~> 10.12.0'
> Update Version to 4.10.12.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.10.13.0.0', partner version '~> 10.13.0'
> Update Version to 4.10.13.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.10.14.0.0', partner version '~> 10.14.0'
> Update Version to 4.10.14.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- README.md
- Source/AdMobAdapter.swift
Adapter version '4.11.0.0.0', partner version '~> 11.0.0'
> Update Version to 4.11.0.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.11.1.0.0', partner version '~> 11.1.0'
> Update Version to 4.11.1.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.11.2.0.0', partner version '~> 11.2.0'
> Update Version to 4.11.2.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.11.3.0.0', partner version '~> 11.3.0'
> Update Version to 4.11.3.0.0

- ChartboostMediationAdapterAdMob.podspec
Change podspec's spec.ios.deployment_target from 11 to 13
> HB-5850: Change iOS target version to 13

- Source/AdMobAdapter.swift
- Source/AdMobAdapterAd.swift
- Source/AdMobAdapterBannerAd.swift
- Source/AdMobAdapterInterstitialAd.swift
- Source/AdMobAdapterRewardedAd.swift
- Source/AdMobAdapterRewardedInterstitialAd.swift
Applied most of the 5.0 changes in a single branch. Missing consent stuff and a few details that need discussion, to be addressed in a separate PR
> Support PartnerAdapter API 5.0 Changes

- Source/AdMobAdapter.swift
- Source/AdMobAdapterBannerAd.swift
Updated implementation for removal of PartnerAdapterFormats.adaptive_banner and additiong of a BannerSize property in PartnerAdLoadRequest
> Remove PartnerAdapterFormat.adaptive_banner

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- README.md
Mediation PR: https://github.com/ChartBoost/helium-ios/pull/1785
> HB-7620: bump the Mediation SDK version to 5.0.0 

- Source/AdMobAdapter.swift
- Source/AdMobAdapterAd.swift
- Source/AdMobAdapterBannerAd.swift
- Source/AdMobAdapterInterstitialAd.swift
- Source/AdMobAdapterRewardedAd.swift
- Source/AdMobAdapterRewardedInterstitialAd.swift
Add support for split of PartnerAd into PartnerBannerAd and PartnerFullscreenAd
> Split PartnerAd into banner and fullscreen

- Source/AdMobAdapter.swift
Added support for new PartnerAdapter consent APIs
> HB-7636: Consent APIs rework

- Source/AdMobAdapter.swift
- Source/AdMobAdapterConfiguration.swift
Adopt new PartnerAdapterConfiguration protocol
> HB-7694: Adapter configuration rework

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.11.5.0.0', partner version '~> 11.5.0'
> Update Version to 4.11.5.0.0

- .github/workflows/release.yml
- .github/workflows/smoke-test.yml
- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- README.md
- Source/AdMobAdapter.swift
Adapter version '4.11.6.0.0', partner version '~> 11.6.0'
> Update Version to 4.11.6.0.0

- CHANGELOG.md
- ChartboostMediationAdapterAdMob.podspec
- Source/AdMobAdapter.swift
Adapter version '4.11.7.0.0', partner version '~> 11.7.0'
> Update Version to 4.11.7.0.0
